# Generated by Django 3.1.3 on 2020-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201205_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
