# Generated by Django 3.1.3 on 2020-12-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
